# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 206ebdcb35d1ac1af35a9b248dc3ba9b23c2947828091180d8b26a64e7d206029cddacf647068a168ca17f492e4692d7015a51b0f89b64f89d390b8b6f5730d6

test:
  secret_key_base: 7eb19b6a259b7423abcb2078ca146f4277d6357e73dc78321f9246e41c547cef43e1ac4b8d79e710c17d2d13952d6e480a7ad6f48fd17393d627c18c1de0c65c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
